In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import string

# 定义字典
char2idx = {s: i for i, s in enumerate(string.ascii_lowercase)}

In [ ]:
eg = "love"
idx = []
for i in eg:
  idx.append(char2idx[i])
idx = torch.tensor(idx)
idx

tensor([11, 14, 21,  4])

In [ ]:
# 使用onehot编码，将文本转换为二维张量
num_claz = len(char2idx.keys())
x = F.one_hot(idx, num_classes = num_claz).float()
x, x.shape

(tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 1., 0., 0., 0., 0.],
         [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0.]]),
 torch.Size([4, 26]))

In [6]:
dims = 5
w = torch.randn(num_claz, dims)
(x @ w), (x @ w).shape

(tensor([[ 0.1719,  0.3692, -0.0995,  0.6196,  0.6720],
         [-0.5233,  0.5258, -0.2037, -0.0173,  0.9902],
         [ 2.2724, -0.2268,  0.5198, -1.7153, -0.5435],
         [ 0.6666, -0.5852, -0.8054, -0.4859, -0.2163]]),
 torch.Size([4, 5]))

In [10]:
w[idx], w[idx].shape, w.shape, idx
# 和上文的结果一致，故而不会多做上面这一步热独编码

(tensor([[ 0.1719,  0.3692, -0.0995,  0.6196,  0.6720],
         [-0.5233,  0.5258, -0.2037, -0.0173,  0.9902],
         [ 2.2724, -0.2268,  0.5198, -1.7153, -0.5435],
         [ 0.6666, -0.5852, -0.8054, -0.4859, -0.2163]]),
 torch.Size([4, 5]),
 torch.Size([26, 5]),
 tensor([11, 14, 21,  4]),
 tensor([ 0.1719,  0.3692, -0.0995,  0.6196,  0.6720]))

In [11]:
class Embedding:

  def __init__(self, num_embeddings, embedding_dim):
    self.weight = torch.randn((num_embeddings, embedding_dim), requires_grad = True)

  def __call__(self, x):
    self.out = self.weight[x]
    return self.out

  def paramters(self):
    return [self.weight]

In [12]:
em = Embedding(num_claz, 5)
x = torch.randint(0, num_claz, (10, ))
em(x).shape

torch.Size([10, 5])

In [13]:
x = torch.randint(0, num_claz, (20, 10))
em(x).shape

torch.Size([20, 10, 5])

In [15]:
for i in range(torch.cuda.device_count()):
  print(torch.cuda.get_device_name(i))

Tesla T4
